### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by cyberpirate92** [cyberpirate92/game-of-life#1]
This is not an actual issue, but just to keep track of how each version looked like.
After every major commit, the screenshot/GIF will be added to this thread.

**Comment by cyberpirate92** [comment]
![gameoflifev1](https://user-images.githubusercontent.com/10222413/29320187-0faba98c-81f4-11e7-8bd5-5a5290cbdbc9.gif)

Commit: ee55c6d239017c3947f9628052cb7ac8763d908f

> ---------

### Major Issues:
- [x] Stats panel (`statsPanel`) is not being rendered. (#2)
- [x] Unicode characters are not being displayed in the `JButton`s. (#3)
- [x] No detection of terminal stages. (#4)

**Comment by cyberpirate92** [comment]
![gameoflifev2](https://user-images.githubusercontent.com/10222413/29358511-ee92eb52-8298-11e7-97c5-cd76f9132293.gif)

Commit: d744ee91be155bb274595e5f849dacfc23e30079

> ------

## Major Issues:

- [x] Reset button not functional. (#6)
- [ ] Percentage change label not getting updated for each generation. (#7)

**Comment by cyberpirate92** [comment]
![screen shot 2017-08-18 at 2 38 40 pm](https://user-images.githubusercontent.com/10222413/29452169-ff3475b2-8422-11e7-8b29-ff0a79326715.png)

Commit: c634f2e2198b4695f010616e70e5fea1b55a0336
